package dbmodel

type DataType int

const (
	Number_t DataType = iota
	Blob_t
	Char_t
	Clob_t
	Date_t
	TimestampTz_t
	Float_t
	Double_t
	Long_t
	Varchar_t
)

type ConstraintType int

const (
	PrimaryKey ConstraintType = iota
	ForeignKey
)

type DbColumnModel struct {
	Name          string
	IsPrimaryKey  bool
	AutoGenerated bool
	Type          DataType
	Nullable      bool
}

type DbConstraintModel struct {
	Name            string
	Type            ConstraintType
	Index           *DbIndexModel
	Columns         []*DbColumnModel
	ReferencedTable *string
}

type DbIndexModel struct {
	Name    string
	Columns []*DbColumnModel
	Unique  bool
}

type DbTableModel struct {
	Name        string
	Columns     []*DbColumnModel
	Indexes     []*DbIndexModel
	Constraints []*DbConstraintModel
}

type DbQueryModel struct {
	Name    string
	Columns []*DbColumnModel
	// Parameters []*
}
